/*
    CAUTION: This code has been generated by AI(GPT-5.6 Sol)
*/

#ifndef SMASHKIDS_RINGBUFFER_HPP
#define SMASHKIDS_RINGBUFFER_HPP

#include <algorithm>
#include <cstddef>
#include <cstring>

class RingBuffer {
public:
    RingBuffer(size_t capacity): mCapacity(capacity), mSize(0), mHead(0), mTail(0) {
        mData = new char[capacity];
    }

    ~RingBuffer() {
        delete[] mData;
    }

    RingBuffer(const RingBuffer&) = delete;
    RingBuffer& operator=(const RingBuffer&) = delete;

    bool IsEmpty() const { return mSize == 0; }
    bool IsFull() const { return mSize == mCapacity; }
    size_t Size() const { return mSize; }
    size_t Capacity() const { return mCapacity; }
    size_t FreeSize() const { return mCapacity - mSize; }

    bool Push(const void* src, size_t len) {
        if(len == 0)
            return true;
            
        if(src == nullptr)
            return false;

        if(len > FreeSize())
            return false;
        
        

        const char* source = static_cast<const char*>(src);

        // push data on single step
        const size_t firstStepLength = std::min(len, mCapacity - mTail);

        std::memcpy(mData + mTail, source, firstStepLength);

        // push data on doubl step

        const size_t secondStepLength = len - firstStepLength;
        if(secondStepLength > 0) {
            std::memcpy(mData, source + firstStepLength, secondStepLength);
        }

        mTail = (mTail + len) % mCapacity;
        mSize += len;
        
        return true;
    }

    bool Pop(size_t len) {
        if (len > mSize)
            return false;
        if (len == 0)
            return true;

        mHead = (mHead + len) % mCapacity;
        mSize -= len;

        if(mSize == 0)
        {
            mHead = 0;
            mTail = 0;
        }

        return true;
    }

    bool Peek(void* dest, size_t len) const {
        if(len == 0) return true;
        
        if(dest == nullptr) return false;

        if(len > mSize) return false;

        char* destination = static_cast<char*>(dest);
        
        // copy data on single step
        const size_t firstStepLength = std::min(len, mCapacity - mHead);

        std::memcpy(destination, mData + mHead, firstStepLength);


        // copy data on double step
        const size_t secondStepLength = len - firstStepLength;
        if(secondStepLength > 0)
        {
            std::memcpy(destination+firstStepLength, mData, secondStepLength);
        }

        return true;
    }

    bool Read(void* dest, size_t len)
    {
        if(!Peek(dest,len))
            return false;
        
        return Pop(len);
    }

    void Clear()
    {
        mHead = 0;
        mTail = 0;
        mSize = 0;
    }

    
private:
    size_t mHead, mTail, mSize, mCapacity;

    char* mData;
};

#endif